version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test1234
      MYSQL_DATABASE: Egeria_2021
      MYSQL_USER: tux
      MYSQL_PASSWORD: Test1234
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_files:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: tux
      WORDPRESS_DB_PASSWORD: Test1234
      WORDPRESS_DB_NAME: Egeria_2021